/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRegionIndexRouteImport } from './routes/_layout/region/index'
import { Route as LayoutProjectIndexRouteImport } from './routes/_layout/project/index'
import { Route as LayoutCategoryIndexRouteImport } from './routes/_layout/category/index'
import { Route as LayoutProjectIdRouteImport } from './routes/_layout/project/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegionIndexRoute = LayoutRegionIndexRouteImport.update({
  id: '/region/',
  path: '/region/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectIndexRoute = LayoutProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoryIndexRoute = LayoutCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectIdRoute = LayoutProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/': typeof LayoutIndexRoute
  '/project/$id': typeof LayoutProjectIdRoute
  '/category': typeof LayoutCategoryIndexRoute
  '/project': typeof LayoutProjectIndexRoute
  '/region': typeof LayoutRegionIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof LayoutIndexRoute
  '/project/$id': typeof LayoutProjectIdRoute
  '/category': typeof LayoutCategoryIndexRoute
  '/project': typeof LayoutProjectIndexRoute
  '/region': typeof LayoutRegionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/project/$id': typeof LayoutProjectIdRoute
  '/_layout/category/': typeof LayoutCategoryIndexRoute
  '/_layout/project/': typeof LayoutProjectIndexRoute
  '/_layout/region/': typeof LayoutRegionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/project/$id'
    | '/category'
    | '/project'
    | '/region'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/project/$id' | '/category' | '/project' | '/region'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/_layout/'
    | '/_layout/project/$id'
    | '/_layout/category/'
    | '/_layout/project/'
    | '/_layout/region/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/region/': {
      id: '/_layout/region/'
      path: '/region'
      fullPath: '/region'
      preLoaderRoute: typeof LayoutRegionIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/project/': {
      id: '/_layout/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof LayoutProjectIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/category/': {
      id: '/_layout/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof LayoutCategoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/project/$id': {
      id: '/_layout/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof LayoutProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectIdRoute: typeof LayoutProjectIdRoute
  LayoutCategoryIndexRoute: typeof LayoutCategoryIndexRoute
  LayoutProjectIndexRoute: typeof LayoutProjectIndexRoute
  LayoutRegionIndexRoute: typeof LayoutRegionIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectIdRoute: LayoutProjectIdRoute,
  LayoutCategoryIndexRoute: LayoutCategoryIndexRoute,
  LayoutProjectIndexRoute: LayoutProjectIndexRoute,
  LayoutRegionIndexRoute: LayoutRegionIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
